### ISSUE TITLE
NSML Session remove 관련 문의

### ISSUE THREAD

**Issue by Chogyuwon** [naver/nlp-challenge#19]
대회 운영에 고생이 많으십니다.

저는 nsml 사용이 이번이 처음인 참가자 입니다.
제가 사용법이 익숙치 않아서 그런건지 모르겠지만...
잘못 생성된 session 을 삭제하고 싶어서 
이번 챌린지 도큐먼트와 이전 해커톤 참가자들이 올린 사용법들을 찾아봤습니다.

$ nsml rm <세션이름>
위의 명령어로 쉽게 삭제가 가능한 것으로 알고 있어 삭제를 해보려고 시도하였으나

제가 받은 nsml  version 에는 nsml command 에 rm 이 없는 것으로 나오고 있습니다. 
사진 첨부합니다.

![screenshot from 2018-11-24 23-26-20](https://user-images.githubusercontent.com/20101790/48969309-65b90e80-f040-11e8-8884-04a9e87dfe36.png)

또한 웹페이지에서도 remove 가 가능한 것으로 알고 있어 이를 시도 하였지만,
성공적으로 삭제됐다는 알림만 나오고 실제로 삭제가 되지 않습니다.

어떻게 해결해야할까요?

**Comment by nsml-admin** [comment]
안녕하세요!
참가 해주셔서 감사합니다.

현재 ```nsml rm``` 명령어는 어뷰징 방지 목적 으로 지원하고있지않습니다.

도큐먼트에서 해당부분 삭제하였습니다

제보감사합니다!

**Comment by nsml-admin** [comment]
네 디버깅을 한 후에는 세션을 재생성해야합니다.

감사합니다.
