### ISSUE TITLE
NSML submit 관련 문의 

### ISSUE THREAD

**Issue by dnjs5649** [naver/nlp-challenge#24]
안녕하세요 지금 해커톤을 하고있는 학생입니다!

제가 submit하는도중 디버깅을 위해 -t 명령어와 함께 실행해보면

....Warning: Your session has a total size of over  10 MB You may want to add unnecessary files and directories to the ignore list. (e.g. the .git directory)
....
Building docker image. It might take for a while
......
Session Max_30/NER/76 is started
....[(0.0, ['-', 'NUM_B', '-', '-']), (0.0, ['DAT_B', '-', 'DAT_B', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'NUM_B', '-', '-']), (0.0, ['ORG_B', 'CVL_B', 'CVL_B', '-', 'NUM_B', '-', '-', 'LOC_B', 'NUM_B', 'NUM_B', 'ORG_B', 'NUM_B', '-', '-', '-', '-']), (0.0, ['-', '-', '-', 'NUM_B', '-', '-', '-', '-', 'NUM_B', '-']), (0.0, ['CVL_B', 'ORG_B', 'ORG_B', 'ORG_I', 'NUM_B', '-', 'NUM_B', '-', '-']), (0.0, ['ORG_B', 'PER_B', '-']), (0.0, ['DAT_B', '-', 'NUM_B', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-']), (0.0, ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-']), (0.0, ['-', '-', '-', '-', '-']), (0.0, ['PER_B', 'DAT_B', '-', '-', '-', '-', '-', '-', '-', '-', 'DAT_B', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'])]

아래와같은 결과가 나오면서 에러가 뜨지 않아 submit을 하려고 실행해본 결과

....Warning: Your session has a total size of over  10 MB You may want to add unnecessary files and directories to the ignore list. (e.g. the .git directory)
....
Building docker image. It might take for a while
........Error: Session does not respond
FATA[2018/11/29 08:48:09.091] Internal server error

이렇게 에러가 나는 모습을 보이고 있습니다 ㅜ 죄송하지만 어떤 오류인지 알수 있을까요??

감사합니다.

**Comment by dnjs5649** [comment]
이곳으로 재질문해서 죄송합니다.
 
제가 submit를 올라간적은 없고 올리는걸 시도하려다가 실패 한적은 있는데 그것도 1시간내로 포함되는지 궁금합니다! 또한 1시간이 지나도 저 상태인데 그러면 코드쪽에 오류로 봐야하나 의문이 들어서 질문 올립니다.
 
감사합니다.
 
참고로 dataset board를 실행하면 아래와 같이 뜹니다.
 
nsml dataset board NER
 
Owner    Score    Submitted    Session    Model    Args
-------  -------  -----------  ---------  -------  ------

 
-----Original Message-----

**Comment by nsml-admin** [comment]
제가 말씀드린 1시간은 submit을해서 제출하신 코드중에 `nsml.bind(infer=infer)`에 전달된 `infer()`함수의 실행 시간을 말씀 드린겁니다. (다른과정들은 거의 시간이 안걸린다고 가정하고 `nsml submit `커맨드가 실행되고 종료되는데 1시간 이상걸렸다면 timeout에 걸렸다고생각하시면됩니다.)

1시간마다 제한되는 서브밋 제한 시간과 위의 에러는 상관이없습니다.

감사합니다.

**Comment by dnjs5649** [comment]
진짜 진짜 죄송합니다 ㅜ 한가지만 더물어보자면!
 
nsml submit 커맨드가 실행되고 종료되는데 1시간 이상걸리면 time out이라는건데 
 
저 저같은 경우는 한 5분만에 위와같은 오류가 뜨는데 그러면 1시간 걸릴것 같아서 취소한건가요? 
 
바쁘신데 죄송합니다. 감사합니다.
 
 
 
-----Original Message-----

**Comment by eagle705** [comment]
저도 같은 에러입니다 ㅠ

**Comment by nsml-admin** [comment]
죄송합니다. 
확인해보니 타임아웃이 제대로 반영이 안 되어 있었고 현재는 타임아웃을 1시간으로 조정해서 inference 타임이 1시간 이내이면 이상 없이 작동 합니다.

번거롭겠지만 다시한번 확인 부탁드립니다. ㅠㅠ 

감사합니다.

**Comment by dnjs5649** [comment]
아 감사합니다!
