### ISSUE TITLE
종료된 세션에 할당된 gpu 사용량 관련 질문입니다!

### ISSUE THREAD

**Issue by Chogyuwon** [naver/nlp-challenge#26]
nsml 사용이 이번이 처음인 참가자입니다.

다름이 아니라, 제가 실수로 만들어 버린 session에서(에러로 인해 user session exit 로그 출력 후 종료 됨)
계속해서 gpu 사용량을 먹고 있습니다. 왜그런것일까요??ㅜㅜ 해결 방법을 알고 싶습니다.

추가적으로 일정 시간 이후에 해당 종료된 세션에 대해서 gpu 사용을 자동으로 멈춘다면
이 세션에 할당된 gpu 사용량 만큼 다른 세션에서 자동으로 나눠 가지게 되는가요?

**Comment by nsml-admin** [comment]
참가해주셔서 감사합니다!

GPU사용량을 먹고있다는 것은 어떻게 확인한 방법인가요? 세션이 종료후 바로는 아니지만 잠시후에  credit 이 감소하는게 멈춥니다.

GPU사용량이란게 정확히 어떤부분을 의미하는지 잘몰라서 크레딧이라고 생각하고 말씀드리겠습니다.

크레딧은 세션이 실행된 시간만큼 차감되고, 1시간마다 60씩 충전되고 있습니다. 특정 세션이 종료된다고 해서 다른 세션에 크레딧이 할당되진 않습니다.

감사합니다.

**Comment by Chogyuwon** [comment]
제가 질문이 조금 모호했던 것 같습니다.

다음과 같이 종료된 세션에 대해서 avg gpu 사용량이 잡히고 있는 것을 보게 되어서...
질문 했습니다.

![default](https://user-images.githubusercontent.com/20101790/49201979-5e01bd00-f3e6-11e8-9799-768d1c245239.PNG)

![1](https://user-images.githubusercontent.com/20101790/49201984-61954400-f3e6-11e8-9694-440f57c719cc.PNG)

**Comment by nsml-admin** [comment]
초반에 사용되었던 사용량으로 생각하시면 되고 현재는 용량을 잡고있지않습니다.

감사합니다
