### ISSUE TITLE
nsml submit 관련 문의

### ISSUE THREAD

**Issue by Chogyuwon** [naver/nlp-challenge#29]
submit -t 옵션을 붙여서 문제 없이 결과 list 가 터미널에 출력되는 것을 확인하고 
해당 세션의 checkpoint 에 대해서 submit을 시도했는데,

....Warning: Your session has a total size of over  10 MB You may want to add unnecessary files and directories to the ignore list. (e.g. the .git directory)
....
Building docker image. It might take for a while
........

이 상태에서 더이상 진행이 되지 않고 있습니다.

docker image 는 nsml/default_ml:cuda9_torch1.0 을 사용했으며
학습 시에 문제가 없었고 -t 옵션을 주고 나서 디버깅도 마친 상태라 왜 그런지 궁금합니다.

지금 infer 함수가 실행되고 있는 것으로 봐야할까요? 
이전 분들 질문을 보니 timeout 이  1시간으로 설정되어 있다곤 하는데
서브밋 제출 한지 1시간이 아직 안되긴 했습니다. 

그렇더라도 메시지만 본다면 아직 도커 이미지도 빌드가 마쳐지지 않은것 같은데 
이미지 빌드가 마쳐지지 않은 것인지 아니면 infer 함수가 test 데이터에 대해서 계산을 하고 있는 중인지 궁금합니다.

**Comment by Chogyuwon** [comment]
해결완료되어 close 하였습니다.
기다리는 것이 답이었네요.

**Comment by eagle705** [comment]
@Chogyuwon 
저도 같은 에러가 있었는데 어떻게 해결하셨는지 궁금합니다ㅜ

**Comment by Chogyuwon** [comment]
아 일단 그냥  40분 ~ 50분 정도 그냥 기다렸습니다.

저는 도커 이미지가 안만들어져서 저 상태에 머물러있는 줄 알았는데 알아서 infer() 함수 실행하고 계산 한 다음에 스코어 뱉어
주더라구요.

중간에 끊어버리면 1시간 동안 제출 못하니까 기다리셔야 합니다 ㅎㅎㅎ

2018년 11월 30일 (금) 오후 4:44, Joosung Yoon <notifications@github.com>님이 작성:
