### ISSUE TITLE
nsml log 관련 문의

### ISSUE THREAD

**Issue by toriving** [naver/nlp-challenge#32]
nsml으로 run을 해놓고 보면 처음에는 잘 되다가 어느 순간

NSML Log start!
Error: Docker daemon timeout!

이런식으로 나옵니다.
이 경우 트레닝이 잘 진행되고있는지 확인할 방법이 있을까요?

**Comment by nsml-admin** [comment]
안녕하세요.

run을 하고난후 로그를 볼때 저런메세지가 출력된건가요?
세션네임을 알려주시면 확인해보겠습니다.

**Comment by toriving** [comment]
State_Of_The_Art/NER/51
State_Of_The_Art/NER/57

두개입니다.
정지시키려고 해도 안되네요.

**Comment by nsml-admin** [comment]
장비 관련 이슈가 있어서 해당 세션의 노드가 재실행 되었고 적정량의 크레딧을 추가해 드렸습니다.

불편을 드려서 죄송합니다.

다시 한번 시도해주시면 감사하겠습니다.
