### ISSUE TITLE
nsml login 관련 문의

### ISSUE THREAD

**Issue by niceparktime** [naver/nlp-challenge#36]
안녕하세요 nsml login을 하려고하니
FATA[2018/12/04 15:53:24. 879] EOF라고 뜹니다.

**Comment by niceparktime** [comment]
![image](https://user-images.githubusercontent.com/45377893/49436244-fe4b4d80-f7fb-11e8-9b94-52f27ba764c3.png)

**Comment by nsml-admin** [comment]
windows환경의 `mingw` 터미널로 보이는데요, 윈도우의 기본 cmd에서 한번 해보실래요?

아니면 `nsml login --username [username] --password [password]` 으로 로그인 시도 부탁드립니다.

감사합니다.
