### ISSUE TITLE
NSML 계정 등록 문의

### ISSUE THREAD

**Issue by skylionking** [naver/nlp-challenge#37]
안녕하세요.

이메일 접근권한을 해제하지 않아 등록이 안된 것 같은데요
등록 여부를 확인할 수 있을까요?

팀 이름은 naverEnding입니다.

**Comment by nsml-admin** [comment]
등록은 일괄적으로 다음날 1시 이후로 되어서요  ~ 지금 하시면 될것입니다.

**Comment by nsml-admin** [comment]
안 될경우 이슈를 다시 열어주세요!
