### ISSUE TITLE
nsml submit 오류

### ISSUE THREAD

**Issue by hpk23** [naver/nlp-challenge#43]
안녕하세요 모델을 학습시키고, submit을 하려고 하는데, 다음과 같은 오류가 나타납니다.

> Error response from daemon: can not get logs from container which is dead or marked for removal

학습도 잘 진행되고, 모델 save도 정상적으로 되는 것 같은데 무엇이 문제인지 알 수 있을까요?
세션 번호는 cheap_learning/SRL/88 입니다.

**Comment by nsml-admin** [comment]
안녕하세요. 전체 로그메세지를보여주실수있나요?

감사합니다
