### ISSUE TITLE
training 중단 문제

### ISSUE THREAD

**Issue by toriving** [naver/nlp-challenge#45]
트레이닝 중 오류가 뜨면서 중단이됩니다.
항상 그런건 아니지만 몇몇 모델이 중단되어 문의합니다

에러는 아래와 같습니다
![image](https://user-images.githubusercontent.com/42434734/49558088-3a41f800-f94d-11e8-9152-ead4fd542352.png)
![image](https://user-images.githubusercontent.com/42434734/49558097-41690600-f94d-11e8-8a2d-97dc796b624f.png)

![image](https://user-images.githubusercontent.com/42434734/49558066-28f8eb80-f94d-11e8-97a5-4699f60b15c3.png)

**Comment by nsml-admin** [comment]
안녕하세요
첫번째에러는 도중에 네트워크가 끊겨서 발생했던 에러같습니다 불편을드려서 죄송합니다 지금은 조치를 취했습니다.
두번째 에러도 비슷하게 장비에 문제가생겨서 조치를 취했습니다.

불편을드려서 죄송합니다 적정량의 크레딧을 추가해드렸습니다.

감사합니다.

**Comment by toriving** [comment]
State_Of_The_Art/NER/179
세션이 오류가 생긴것같습니다.
삭제부탁드립니다.

**Comment by Chogyuwon** [comment]
저 또한 해당에러가 발생하면서 학습중이던 세션이 종료되었습니다.

또한 submit 시에

....Warning: Your session has a total size of over  10 MB You may want to add unnecessary files and directories to the ignore list. (e.g. the .git directory)
....
Building docker image. It might take for a while
........Error: Session does not respond
FATA[2018/12/07 13:01:09.315] Internal server error           

다음과 같은 에러가 뜨면서 최종적으로 제출이 안되는 상황인데요...

이게 바로 뜨면 코드의 문제인가 싶을 수 있는데 제출 후 1시간 다 되어갈 때쯤 발생합니다.

submit -t 옵션 주었을 때 문제 없이 list 반환이 되었었는데

gyuwonable/NER/114 세션입니다.

확인 부탁 드리겠습니다.

**Comment by lsrock1** [comment]
모든 세션에서 2 에폭 nsml.save때 이 분과 같은 에러가 나는데요 뭔가 잘못한 것이 있나요?
