### ISSUE TITLE
docker 에러

### ISSUE THREAD

**Issue by seanie12** [naver/nlp-challenge#47]
다음과 같은 에러가 나면서 실행이 안되는데 무엇이 문제인가요?

Name        Size     Last Modified    Author    Description        Tag
----------  -------  ---------------  --------  -----------------  -----
NER         18.5 MB  16 days ago      nsmlteam
SRL         7.59 MB  12 days ago      nsmlteam
hello_nsml  10 KB    16 days ago      nsmlteam  nsml test dataset

D:\downloads\nsml_client.windows.amd64.hack>nsml run -e naver-ner/main.py -d NER
INFO[2018/12/06 13:41:02.026] file integrity check - start
INFO[2018/12/06 13:41:02.039] file integrity check - done
INFO[2018/12/06 13:41:02.047] .gitignore 1.3 KiB - start
INFO[2018/12/06 13:41:02.052] .gitignore 1.3 KiB - done (1/12 8.33%) (1.3 KiB/39 MiB 0.00%)
INFO[2018/12/06 13:41:02.058] .nsmlignore 19 B - start
INFO[2018/12/06 13:41:02.061] .nsmlignore 19 B - done (2/12 16.67%) (1.3 KiB/39 MiB 0.00%)
INFO[2018/12/06 13:41:02.067] LICENSE 11 KiB - start
INFO[2018/12/06 13:41:02.071] LICENSE 11 KiB - done (3/12 25.00%) (13 KiB/39 MiB 0.03%)
INFO[2018/12/06 13:41:02.075] README.md 40 B - start
INFO[2018/12/06 13:41:02.078] README.md 40 B - done (4/12 33.33%) (13 KiB/39 MiB 0.03%)
INFO[2018/12/06 13:41:02.081] data_loader.py 1.1 KiB - start
INFO[2018/12/06 13:41:02.086] data_loader.py 1.1 KiB - done (5/12 41.67%) (14 KiB/39 MiB 0.03%)
INFO[2018/12/06 13:41:02.091] dataset_batch.py 10 KiB - start
INFO[2018/12/06 13:41:02.095] dataset_batch.py 10 KiB - done (6/12 50.00%) (24 KiB/39 MiB 0.06%)
INFO[2018/12/06 13:41:02.098] evaluation.py 5.3 KiB - start
INFO[2018/12/06 13:41:02.102] evaluation.py 5.3 KiB - done (7/12 58.33%) (29 KiB/39 MiB 0.07%)
INFO[2018/12/06 13:41:02.106] main.py 8.6 KiB - start
INFO[2018/12/06 13:41:02.111] main.py 8.6 KiB - done (8/12 66.67%) (38 KiB/39 MiB 0.09%)
INFO[2018/12/06 13:41:02.114] model.py 8.7 KiB - start
INFO[2018/12/06 13:41:02.118] model.py 8.7 KiB - done (9/12 75.00%) (46 KiB/39 MiB 0.12%)
INFO[2018/12/06 13:41:02.124] necessary.pkl 39 MiB - start
INFO[2018/12/06 13:41:10.128] necessary.pkl 39 MiB - done (10/12 83.33%) (39 MiB/39 MiB 100.00%)
INFO[2018/12/06 13:41:10.135] setup.py 259 B - start
INFO[2018/12/06 13:41:10.139] setup.py 259 B - done (11/12 91.67%) (39 MiB/39 MiB 100.00%)
INFO[2018/12/06 13:41:10.143] tt.py 370 B - start
INFO[2018/12/06 13:41:10.146] tt.py 370 B - done (12/12 100.00%) (39 MiB/39 MiB 100.00%)
..Warning: Your session has a total size of over  10 MB You may want to add unnecessary files and directories to theignore list. (e.g. the .git directory)
...
Building docker image. It might take for a while
...nlp_pln/NER/1: launching is failed
[nlp_pln/NER/1]
Stopping nlp_pln/NER/1 is failed
Done
Error: Fail to start docker container: b''
FATA[2018/12/06 13:41:17.440] Internal server error

**Comment by nsml-admin** [comment]
위세션이 할당된 장비에 문제가 있었던거같습니다.

다시 시도해보실래요?

감사합니다.
