### ISSUE TITLE
session submit 오류

### ISSUE THREAD

**Issue by Chogyuwon** [naver/nlp-challenge#49]
submit 하는 중에 

....Warning: Your session has a total size of over 10 MB You may want to add unnecessary files and directories to the ignore list. (e.g. the .git directory)
....
Building docker image. It might take for a while
........Error: Session does not respond
FATA[2018/12/07 13:01:09.315] Internal server error

다음과 같은 에러가 뜨면서 최종적으로 제출이 안되는 상황인데요...

이게 바로 뜨면 코드의 문제인가 싶을 수 있는데 제출 후 1시간 다 되어갈 때쯤 발생합니다.
혹시 test 코드 시간 문제일까요??

기존 모델에 비해서 특별히 수정한 것이 많이 없었어서 잘 제출 되던 것이 제출이 안되서
답답합니다ㅠㅠㅠ

submit -t 옵션 주었을 때 문제 없이 list 반환이 되었었는데 왜 그런 것일까요ㅠ
gyuwonable/NER/114 세션 0 번 checkpoint 입니다.

확인 부탁 드리겠습니다.

추가 적으로 해당 모델 제출 후 아래 링크의 오류와 같은 에러메시지가 발생하며
학습중이던 세션이 종료되었습니다.

https://github.com/naver/nlp-challenge/issues/45

**Comment by nsml-admin** [comment]
안녕하세요.

위 문제는 1시간 이내에 결과값을 받아오지 못할때 발생되는 문제입니다.
 
학습중이던 세션이 종료된 경우는 네트워크 문제로보이는데요, 현재 원인파악중 이고 세션번호를 알려주시면 적절한 크레딧을 추가해드리겠습니다.

불편을드려서 죄송합니다
