### ISSUE TITLE
nsml 외부 리소스 사용 문의

### ISSUE THREAD

**Issue by monologg** [naver/nlp-challenge#50]
안녕하세요 이번 대회에서 주어진 데이터 이외에 pretrained embedding등의 외부 리소스를 같이 사용하려고 하는데,  해당 리소스를 올리려고 할 때 50 MiB 이상은 올릴 수 없다고 나와있는데, 다른 이슈에서는 5GB까지는 허용한다는 글을 본걸로 기억하고 있습니다. 혹시 앞으로도 50MiB 이상을 초과해서는 외부리소스를 올릴수 없는건지, 아니면 다른 방법이 있는지 해서 문의 올립니다.

감사합니다.

$ nsml run --show-limits
>maximum number of files: 100
>maximum total size of files: 50 MiB
>maximum size of a single queueable file: 4.0 MiB

**Comment by nsml-admin** [comment]
안녕하세요.
방법은 여러가지가 있겠는데요,
1. embedding 파일을 어딘가에 올려놓고 세션내에서 해당파일을 가져오는방법이 있겠습니다.
2. embedding 파일이 보관된 도커이미지를 만든후 nsml에서 해당이미지를 실행환경으로 셋팅하면됩니다.

감사합니다.
