### ISSUE TITLE
docker image error "No such container:"

### ISSUE THREAD

**Issue by jinhan** [naver/nlp-challenge#52]
https://github.com/naver/nlp-challenge/issues/38 을 참고하여 docker hub의 image를 이용하거나,
setup.py에서 baseline으로 사용되는 ```# nsml: nsml/default_ml:tf-1.4.1``` 사용할 때도 
다음과 같은 에러가 계속 발생합니다.

<img width="513" alt="2018-12-09 8 13 44" src="https://user-images.githubusercontent.com/3071179/49691647-86c64700-fb8a-11e8-9208-fc871a351cbc.png">

```python
# nsml: nsml/default_ml:tf-1.4.1
# nsml: tensorflow/tensorflow:1.11.0-gpu-py3

from distutils.core import setup
```
setup.py에서 이렇게 하면 tf-1.4.1이 로드되어야하는데, error가 발생하면서 1.4.0으로 확인됩니다.

**Comment by nsml-admin** [comment]
안녕하세요.

`# nsml: ` 대신에 `#nsml: ` 로 설정을 바꿔주실래요?

감사합니다.
