### ISSUE TITLE
nsml submit 오류 관련 문의

### ISSUE THREAD

**Issue by Chogyuwon** [naver/nlp-challenge#53]
submit 도중에 아래와 같은 에러 메시지가 나오게 되어 질문드립니다.
그 동안 한번도 본적 없던 에러라 어떤 이유로 발생한 것인지 알고 싶습니다.

제출 시간은 1시간이 되지 않은 시점에서 발생했기 때문에 시간 초과 오류는 아닌 것 같은데...
무슨 오류인가요?

Building docker image. It might take for a while
........FATA[2018/12/09 13:19:29.972] execute interactive failed: rpc error: code = Unavailable desc = transport is closing

**Comment by nsml-admin** [comment]
안녕하세요

혹시 submit도중 네트워크가 끊기거나 변경되지는 않았는지요.? 
해당에러는 네트워크관련된 에러로 보입니다.

감사합니다.
