### ISSUE TITLE
홈페이지 nsml submit 실패시 1시간 잠김

### ISSUE THREAD

**Issue by Kcrong** [naver/nlp-challenge#57]
홈페이지에서 submit을 할 경우, fail to ~~ 라고 뜨면서 1시간동안 잠겨버립니다.

하지만 terminal 에서 시도하면 잘 되는 경우가 많은데요, 혹시 홈페이지 버튼 이벤트에 대한 1시간 잠금을 풀어주실 수 있나요? 실수로 submit을 누르면 1시간 동안 잠기게 되어, 매우 불편합니다.

**Comment by Kcrong** [comment]
또한, submit이 진행되지 않습니다.

```bash
$ nsml submit LuDeKris/NER/121 6
........
Building docker image. It might take for a while
........Error: Session does not respond
FATA[2018/12/10 23:04:33.283] Internal server error
```

**Comment by Kcrong** [comment]
위와 같은 이슈가 지금도 발생합니다. -t 옵션으로 진행시 원활히 결과가 나옵니다.

**Comment by Kcrong** [comment]
```bash
$ nsml submit LuDeKris/NER/201 8
........
Building docker image. It might take for a while
........Error: Session does not respond
FATA[2018/12/11 22:06:27.869] Internal server error
```

**Comment by nsml-admin** [comment]
안녕하세요.

로그를 확인해보니 
`LuDeKris/NER/201` 세션의 경우 submit타임이 1시간이 초과되어서 에러가난경우입니다.

웹 interface부분에 관한건 참고하도록 하겠습니다. 제보감사드립니다.

감사합니다.

**Comment by Kcrong** [comment]
확인 감사드립니다.
