### ISSUE TITLE
세션 사라짐 현상

### ISSUE THREAD

**Issue by Kcrong** [naver/nlp-challenge#59]
![image](https://user-images.githubusercontent.com/13450715/49777720-03048a00-fd45-11e8-8980-8eaa1f9c647d.png)

153번 이후 새로돌린 세션이 왼쪽 목록에 뜨지 않습니다. 
터미널 출력은 다음과 같습니다.
```bash
........
Building docker image. It might take for a while
......
Session LuDeKris/NER/161 is started
.
Error: Error occurred while loading model
FATA[2018/12/11 13:01:53.106] Internal server error
```

확인 부탁드립니다.

**Comment by nsml-admin** [comment]
안녕하세요 참가해주셔서 감사합니다.

153번 이후로 실행한 세션이 목록에 뜨지않는다는게 nsml run으로 실행한 세션이 목록에 뜨지않는건가요.?

터미널 출력을보니 submit이나 fork로 한걸로 보이는데요, 세션을 생성하다 실패하면 목록에 보이지는 않습니다.

감사합니다.

**Comment by Kcrong** [comment]
답변 감사합니다. 혹시 세션에 대한 submit이 진행되지 않아, (별도의 에러 메세지도 뜨지 않는 상황입니다.)
혹시 원인을 봐주실 수 있으실까요?

`LuDeKris/NER/154` 세션에서 4 epoch 를 submit 했습니다.

**Comment by nsml-admin** [comment]
네 확인해보겠습니다.

**Comment by nsml-admin** [comment]
@Kcrong  

에러는 모델을 load할때 발생한것이고, 자세한 내용은 메일로 답변드렸습니다.

감사합니다.

**Comment by Kcrong** [comment]
동작합니다. 감사합니다
