### ISSUE TITLE
SRL 데이터 관련 문의입니다!

### ISSUE THREAD

**Issue by LangtechKHMin** [naver/nlp-challenge#6]
안녕하세요!
제공해주신 훈련데이터와 개괄적 설명에 대한 글을 확인하는 과정에 문의사항이 생겨서 글을 남기게 되었습니다.
Supervised learning이라면 공개된 훈련데이터가 태깅이 완료된 답이라는 가정을 해야 하는데, 훈련데이터의 태깅된 결과들을 살펴보면 정해주신 17개의 의미역 중 하나에 속하지만 레이블이 없이 "-"로 표기된 경우가 많이 보이며, 제일 단적인 예시로 "의미역 결정" 리더보드에 있는

그는 ARG0
경찰에게 -
신분증을 ARG1
보였다 -

의 경우,
"보이다" 라는 용언의 행위주, 피동작주만 레이블링이 되어 있고,
"경찰에게" 라는 ARG3의 가능성이 있는 어절의 경우 레이블링이 되어 있지 않은 것을 확인할 수 있습니다.
훈련 데이터 내에도 이와 같이 ARGM-OOO에 대한 레이블링은 완전하지 않아 보이기에 혹시 이들 훈련 데이터 역시 살펴보고 레이블링을 해야 하는지, 아니면 단순히 이들이 답이라 가정하고 진행을 해야할 지 여쭤보기 위해 글을 남기게 되었습니다.

긴 글 읽어주셔서 정말 감사드립니다.

P.S. 또한 ARGM-TMP의 경우 '용언이 행해지는 시제'라고 하셨는데, 이는 '보였다'라는 용언의 활용형에 내재되어 있기에 이 또한 표기가 되어야 의미역의 연관성을 명확히 확인할 수 있을 것이라 생각하지만 이는 용언에 내재된 경우라서 어절 단위로 레이블링을 하는 데에 제한이 있기에 제외되어 표기된 것인지도 궁금합니다! 다른 ARGM-TMP로 태깅된 데이터를 봤을 때, 어절 전체가 시점과 관계가 있는 것들이 대부분인데 "과거-현재-미래"를 의미하는 시제라고 설명에 적혀있기에 이것에 대한 명확한 정의를 여쭙고자 합니다!

**Comment by cwnu-airlab** [comment]
1. 코퍼스의 오류에 관하여

많이 정제를 수행한 코퍼스이지만, 일부 오류가 포함되어 있을 수 있습니다.
현재 배포된 코퍼스를 수정 재배포시, 다른 팀의 기 학습된 모델과는 다른 코퍼스가 적용될 수 있으므로 경진 대회가 시작한 현시점에서 수정하여 반영하기가 어려움을 양해 부탁드립니다. 대신 평가 코퍼스에는 이런 문장 오류가 포함되어 있지 않도록 구성하여 평가될 수 있도록 하겠습니다.
코퍼스 오류를 수정하여 공식적인 배포는 어렵지만, 오류로 간주되는 정답을 수정하여 참가자 모델에 반영하는 것은 자유롭게 진행하셔도 좋을 것 같습니다.

2. ARGM-TMP에 관하여

의미역 결정 문제는 용언과 논항(augument) 사이의 관계를 파악하는 문제입니다. 따라서 말씀하신 용언의 시제는 의미역 분석의 대상이 아닙니다. 시제 이외에도 용언은 논항이 아니기에 어떠한 태그도 부착되지 않습니다. ARGM-TMP는 '시간' 의미의 논항에 부착하는 태그로써 이를테면 '어제 철수를 만났다.'에서의 '어제'나, '94년도에 태어났다.'의 '94년도에'가 ARGM-TMP에 해당하겠습니다.

**Comment by cwnu-airlab** [comment]
감사합니다. 이슈를 닫도록 하겠습니다.
