### ISSUE TITLE
데이터 용량 문의

### ISSUE THREAD

**Issue by iedcon** [naver/nlp-challenge#61]
안녕하세요
아래 이슈들을 참고했을 때, 5GB까지 용량을 사용할 수 있다고 이해하였는데,
![image](https://user-images.githubusercontent.com/23474550/49782484-da3abf80-fd59-11e8-89fc-60ce97751f5d.png)
형태의 메시지가 뜨면서 50MiB를 초과할 수 없다고 합니다. 실제로 50MB가 넘는 word_embedding을 사용할 수 없는 것인지요?

**Comment by nsml-admin** [comment]
안녕하세요

https://github.com/naver/nlp-challenge/issues/50

이 이슈를 참조하시면 될것같습니다.

추가로 제가 해당이슈 1번에 애매하게 답을한것같은데요,

embedding파일을 세션내에서 파이썬코드로 접근해서 가져오는방법을 말하는것입니다.

감사합니다

**Comment by iedcon** [comment]
해결되었습니다. 감사합니다.
