### ISSUE TITLE
infer 최종 출력 양식

### ISSUE THREAD

**Issue by Kcrong** [naver/nlp-challenge#68]
[여기](https://github.com/naver/nlp-challenge/tree/master/missions/ner#infer-%EC%B5%9C%EC%A2%85-%EB%B0%98%ED%99%98-%EC%B6%9C%EB%A0%A5-%ED%98%95%EC%8B%9D)를 보고 최종 infer 반환 결과는 prob과 output을 zip한 결과라고 이해했습니다.

다만 예제를 참고했을 때 단순히 0으로 zip 하던데, 어떤 의미가 있는건가요?

1. prob, output 에서 prob의 의미가 무엇인가요?
2. 예제처럼 단순히 0으로 zip 해도 되는건가요?
3. 훈련시에 val data기준 f1 score가 0.9대로 나오는데, (모델을 다운로드해서 직접 돌려봐도 reasonable 한 결과가 나옵니다.) 실제 submit을 해보면 score가 0으로 나옵니다. 이건 return format이 잘못되어 나오는 문제인가요?

**Comment by Kcrong** [comment]
submit과 model download를 시도해본 모델은 LuDeKris/NER/229 세션의 모델입니다.

**Comment by Kcrong** [comment]
@nsml-admin 수차례 `submit -t`로 확인했음에도 불구하고 README에서 나온 output과 다름을 찾지 못했습니다. 

혹시 점수가 0이 나오는 이유를 시스템상에서 확인해주실 수 있으신가요?
가령
1. overfitting 등의 이유로 점수가 낮아서 
2. 포맷등의 오류가 나서
3. 기타 등

또한, 위 경우를 알수있는 경고/오류 메세지가 있을까요?

**Comment by nsml-admin** [comment]
evaluate할때 아래의 링크처럼 '_'를 기준으로 split을한후 2개의 값을 리턴받는데,리턴결과중 `_PAD_` 같이 3개의값을 리턴받아서 에러가발생하여 0점처리되었습니다 해당부분 수정부탁드립니다.

https://github.com/naver/nlp-challenge/blob/master/missions/ner/evaluation.py#L80

감사합니다.

**Comment by Kcrong** [comment]
수정후, 작동확인했습니다. 감사합니다
