### ISSUE TITLE
세션 삭제에 대해서 및 세션 timeout에 대해서

### ISSUE THREAD

**Issue by sjkoo1989** [naver/nlp-challenge#72]
기존의 필요없는 세션을 삭제할 수 있는 방법이 있을까요?

**Comment by sjkoo1989** [comment]
아울러 원래 -t 옵션으로 submit test를 하면 paused 되고 Internal Error로 끝나는 것이 맞는지도 여쭈어봅니다. 테스트 제출이 끝나면 정상 메세지가 보여지는지 궁금합니다.

**Comment by nsml-admin** [comment]
안녕하세요.

현재 보안상 세션을 삭제하는 기능은 지원하고있지않습니다.

-t 옵션으로 test를 하면, 정상적이라면 paused되고, `infer` 함수가 실행된후 return된 값들을 확인할수있습니다.

그렇지 않다면,  Internal Error로 끝나면서 에러로 됩니다.

감사합니다.
