### ISSUE TITLE
nsml 사이트 접근 관련 문의

### ISSUE THREAD

**Issue by toriving** [naver/nlp-challenge#80]
발표 자료를 만드려고 개인 리더보드를 보고싶은데 nsml 사이트 접근이 안됩니다.
혹시 사이트를 접근할 수 있도록 해주시거나 개인 기록들을 확인 할 수 있는 방법이 있을까요?

**Comment by nsml-admin** [comment]
메일로 보내드렸습니다
감사합니다.
